# Generated by Django 4.1.5 on 2023-01-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="14B99B4A", max_length=8, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[(1, "VISA"), (2, "MASTERCARD")], max_length=20
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[(1, "RUB"), (2, "USD"), (3, "EUR")], max_length=20
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sendler", models.CharField(max_length=20)),
                ("reciever", models.CharField(max_length=20)),
                (
                    "transfer_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("commision", models.DecimalField(decimal_places=2, max_digits=20)),
                ("status", models.CharField(default="PAID", max_length=300)),
                ("crompleted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.wallet"
                    ),
                ),
            ],
        ),
    ]
