# Generated by Django 4.1.5 on 2023-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="DEBFD774", max_length=8, unique=True),
        ),
    ]
